/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'
import { Route as ApiAiRouteImport } from './routes/api/ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/email' | '/research' | '/responsible-ai' | '/api/ai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/email' | '/research' | '/responsible-ai' | '/api/ai'
  id: '__root__' | '/' | '/email' | '/research' | '/responsible-ai' | '/api/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailRoute: typeof EmailRoute
  ResearchRoute: typeof ResearchRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
  ApiAiRoute: typeof ApiAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailRoute: EmailRoute,
  ResearchRoute: ResearchRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
  ApiAiRoute: ApiAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
